samples:
  tumor1:  /filepath/tumor1.bam
  normal1:  /filepath/normal1.bam
  tumor2:  /filepath/tumor2.bam
  normal2:  /filepath/normal2.bam

pairings: #format is tumor_name: normal_name
  tumor1:  normal1
  tumor2:  normal2
